const int c1=10;
const int c2=9;
const int c3=8;
const int c4=7;
const int c5=6;
const int c6=5;
const int c7=4;
const int c8=3;
const int c9=2;
const int n1=11;
const int n2=12;
const int n3=13;

void setup()
{
  pinMode(c1, OUTPUT);
  pinMode(c2, OUTPUT);
  pinMode(c3, OUTPUT);
  pinMode(c4, OUTPUT);
  pinMode(c5, OUTPUT);
  pinMode(c6, OUTPUT);
  pinMode(c7, OUTPUT);
  pinMode(c8, OUTPUT);
  pinMode(c9, OUTPUT);
  pinMode(n1, OUTPUT);
  pinMode(n2, OUTPUT);
  pinMode(n3, OUTPUT);
}

void loop()
{
  digitalWrite(n1,HIGH);
  digitalWrite(c1,HIGH);
  delay(150);
  digitalWrite(c1,LOW);
  digitalWrite(c2,HIGH);
  delay(150);
  digitalWrite(c2,LOW);
  digitalWrite(c3,HIGH);
  delay(150);
  digitalWrite(c3,LOW);
  digitalWrite(c4,HIGH);
  delay(150);
  digitalWrite(c4,LOW);
  digitalWrite(c5,HIGH);
  delay(150);
  digitalWrite(c5,LOW);
  digitalWrite(c6,HIGH);
  delay(150);
  digitalWrite(c6,LOW);
  digitalWrite(c7,HIGH);
  delay(150);
  digitalWrite(c7,LOW);
  digitalWrite(c8,HIGH);
  delay(150);
  digitalWrite(c8,LOW);
  digitalWrite(c9,HIGH);
  delay(150);
  digitalWrite(c9,LOW);
  digitalWrite(n1,LOW);
  digitalWrite(n2,HIGH);
  digitalWrite(c1,HIGH);
  delay(150);
  digitalWrite(c1,LOW);
  digitalWrite(c2,HIGH);
  delay(150);
  digitalWrite(c2,LOW);
  digitalWrite(c3,HIGH);
  delay(150);
  digitalWrite(c3,LOW);
  digitalWrite(c4,HIGH);
  delay(150);
  digitalWrite(c4,LOW);
  digitalWrite(c5,HIGH);
  delay(150);
  digitalWrite(c5,LOW);
  digitalWrite(c6,HIGH);
  delay(150);
  digitalWrite(c6,LOW);
  digitalWrite(c7,HIGH);
  delay(150);
  digitalWrite(c7,LOW);
  digitalWrite(c8,HIGH);
  delay(150);
  digitalWrite(c8,LOW);
  digitalWrite(c9,HIGH);
  delay(150);
  digitalWrite(c9,LOW);
  digitalWrite(n2,LOW);
  digitalWrite(n3,HIGH);
  digitalWrite(c1,HIGH);
  delay(150);
  digitalWrite(c1,LOW);
  digitalWrite(c2,HIGH);
  delay(150);
  digitalWrite(c2,LOW);
  digitalWrite(c3,HIGH);
  delay(150);
  digitalWrite(c3,LOW);
  digitalWrite(c4,HIGH);
  delay(150);
  digitalWrite(c4,LOW);
  digitalWrite(c5,HIGH);
  delay(150);
  digitalWrite(c5,LOW);
  digitalWrite(c6,HIGH);
  delay(150);
  digitalWrite(c6,LOW);
  digitalWrite(c7,HIGH);
  delay(150);
  digitalWrite(c7,LOW);
  digitalWrite(c8,HIGH);
  delay(150);
  digitalWrite(c8,LOW);
  digitalWrite(c9,HIGH);
  delay(150);
  digitalWrite(c9,LOW);
  digitalWrite(n3,LOW);
}

